# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eab2bc344cd1cdba4caeabf59040aef30bd927b198102a40d7f12eb11e8d6cf0aa6aa1b58978e8381e4fbc993947df59d3eea335bd8f5272917cf3077176021

test:
  secret_key_base: 901439d12de3d3e13f547e423b12cd02a78b10b8c4c71af0d02155444056664b17538d2385916231fc7db3f066852e613bbe89e7395bc243b2ffb0ff5c64774e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
